# Use the README file as a reference to customize settings.

User:
  fields:
    default: login, name, money
    form: login, name, money
  relationships: items, inventories
  application: Application
